// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// KGE2011cpp
double KGE2011cpp(std::vector<double> x, std::vector<double> y);
RcppExport SEXP _poof_KGE2011cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(KGE2011cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// NSEcpp
double NSEcpp(std::vector<double> x, std::vector<double> y);
RcppExport SEXP _poof_NSEcpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(NSEcpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// LMEcpp
double LMEcpp(std::vector<double> x, std::vector<double> y);
RcppExport SEXP _poof_LMEcpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(LMEcpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// mm_d_m3_s
std::vector<double> mm_d_m3_s(std::vector<double> mm, std::vector<double> area);
RcppExport SEXP _poof_mm_d_m3_s(SEXP mmSEXP, SEXP areaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type mm(mmSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type area(areaSEXP);
    rcpp_result_gen = Rcpp::wrap(mm_d_m3_s(mm, area));
    return rcpp_result_gen;
END_RCPP
}
// mm_d_m3_d
std::vector<double> mm_d_m3_d(std::vector<double> mm, std::vector<double> area);
RcppExport SEXP _poof_mm_d_m3_d(SEXP mmSEXP, SEXP areaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type mm(mmSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type area(areaSEXP);
    rcpp_result_gen = Rcpp::wrap(mm_d_m3_d(mm, area));
    return rcpp_result_gen;
END_RCPP
}
// m3_s_mm_d
std::vector<double> m3_s_mm_d(std::vector<double> mm, std::vector<double> area);
RcppExport SEXP _poof_m3_s_mm_d(SEXP mmSEXP, SEXP areaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type mm(mmSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type area(areaSEXP);
    rcpp_result_gen = Rcpp::wrap(m3_s_mm_d(mm, area));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_poof_KGE2011cpp", (DL_FUNC) &_poof_KGE2011cpp, 2},
    {"_poof_NSEcpp", (DL_FUNC) &_poof_NSEcpp, 2},
    {"_poof_LMEcpp", (DL_FUNC) &_poof_LMEcpp, 2},
    {"_poof_mm_d_m3_s", (DL_FUNC) &_poof_mm_d_m3_s, 2},
    {"_poof_mm_d_m3_d", (DL_FUNC) &_poof_mm_d_m3_d, 2},
    {"_poof_m3_s_mm_d", (DL_FUNC) &_poof_m3_s_mm_d, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_poof(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
