# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Kling-Gupta Efficiency
#'
#' @description Kling-Gupta efficiency function
#'
#' @param x numeric vector
#' @param y numeric vector of same length as x
#' 
#' @return KGE value
#'
kge <- function(x, y) {
    .Call(`_poof_kge`, x, y)
}

hbv <- function(x) {
    .Call(`_poof_hbv`, x)
}

api <- function(P, k, t) {
    .Call(`_poof_api`, P, k, t)
}

#' [m3/d] to [mm] convert 
NULL

#' [mm] to [m3/s] convert 
#'
#' @param mm milimeters
#' @param area in square kilometers
#'
#'
mm_d_m3_s <- function(mm, area) {
    .Call(`_poof_mm_d_m3_s`, mm, area)
}

#' [mm] to [m3/d] convert 
#'
#' @param mm milimeters
#' @param area in square kilometers
#'
#'
mm_d_m3_d <- function(mm, area) {
    .Call(`_poof_mm_d_m3_d`, mm, area)
}

m3_s_mm_d <- function(mm, area) {
    .Call(`_poof_m3_s_mm_d`, mm, area)
}

